-- 013_storage.sql
-- NOTE: File storage is now handled by Amazon S3 (bucket: aurami-family-assets)
-- No database storage tables needed. S3 bucket should be created via AWS Console or CloudFormation.
-- Asset metadata is tracked in the 'assets' table (005_assets_media.sql).
